/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OurCraftRouteImport } from './routes/our-craft'
import { Route as CustomBuildsRouteImport } from './routes/custom-builds'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ShopCategorySlugRouteImport } from './routes/shop.category.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OurCraftRoute = OurCraftRouteImport.update({
  id: '/our-craft',
  path: '/our-craft',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomBuildsRoute = CustomBuildsRouteImport.update({
  id: '/custom-builds',
  path: '/custom-builds',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategorySlugRoute = ShopCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-builds': typeof CustomBuildsRoute
  '/our-craft': typeof OurCraftRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-builds': typeof CustomBuildsRoute
  '/our-craft': typeof OurCraftRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-builds': typeof CustomBuildsRoute
  '/our-craft': typeof OurCraftRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-builds'
    | '/our-craft'
    | '/shop'
    | '/wishlist'
    | '/shop/$slug'
    | '/shop/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-builds'
    | '/our-craft'
    | '/shop'
    | '/wishlist'
    | '/shop/$slug'
    | '/shop/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-builds'
    | '/our-craft'
    | '/shop'
    | '/wishlist'
    | '/shop/$slug'
    | '/shop/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomBuildsRoute: typeof CustomBuildsRoute
  OurCraftRoute: typeof OurCraftRoute
  ShopRoute: typeof ShopRouteWithChildren
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-craft': {
      id: '/our-craft'
      path: '/our-craft'
      fullPath: '/our-craft'
      preLoaderRoute: typeof OurCraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-builds': {
      id: '/custom-builds'
      path: '/custom-builds'
      fullPath: '/custom-builds'
      preLoaderRoute: typeof CustomBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/category/$slug': {
      id: '/shop/category/$slug'
      path: '/category/$slug'
      fullPath: '/shop/category/$slug'
      preLoaderRoute: typeof ShopCategorySlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopCategorySlugRoute: typeof ShopCategorySlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopCategorySlugRoute: ShopCategorySlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomBuildsRoute: CustomBuildsRoute,
  OurCraftRoute: OurCraftRoute,
  ShopRoute: ShopRouteWithChildren,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
