ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_amount NUMERIC DEFAULT 0;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS total NUMERIC DEFAULT 0;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount NUMERIC DEFAULT 0;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_code TEXT;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS promo_code TEXT;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal NUMERIC DEFAULT 0;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS transaction_id TEXT;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_proof_url TEXT;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS deposit_amount NUMERIC DEFAULT 0;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS remaining_amount NUMERIC DEFAULT 0;